#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightTop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightBottom,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftTop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftBottom,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

static const int upSpeed = 127;
static const int downSpeed = -64;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  		//Assigns the value of the Y1 axis to the left motor
		motor[leftDrive] = vexRT[Ch3];
		//Assigns the value of the Y2 axis to the right motor
		motor[rightDrive] = vexRT[Ch2];

		//If button 6 up (right bumper) is pressed
		if(vexRT[Btn6U] == 1)
		{
			//Raise the arm
			motor[rightTop] = upSpeed;
			motor[rightBottom] = upSpeed;
		}
		//Else, if button 6 down (right trigger) is pressed
		else if(vexRT[Btn6D] == 1)
		{
			//Lower the arm
			motor[rightTop] = downSpeed;
			motor[rightBottom] = downSpeed;
		}
		//Else (no button pressed)
		else
		{
			//Turn the arm motor off
			motor[rightTop] = 0;
			motor[rightBottom] = 0;
		}

		if(vexRT[Btn5U] == 1)
		{
			//Raise the arm
			motor[leftTop] = upSpeed;
			motor[leftBottom] = upSpeed;
		}
		//Else, if button 6 down (right trigger) is pressed
		else if(vexRT[Btn5D] == 1)
		{
			//Lower the arm
			motor[leftTop] = downSpeed;
			motor[leftBottom] = downSpeed;
		}
		//Else (no button pressed)
		else
		{
			//Turn the arm motor off
			motor[leftTop] = 0;
			motor[leftBottom] = 0;
		}

		// 7L / 7R controls the hand
		if(vexRT[Btn7L] == 1)
			motor[claw] = 100;
		else if(vexRT[Btn7R] == 1)
			motor[claw] = -100;
		else
			motor[claw] = 0;
  }
}
