#pragma config(Motor,  port2,           DriveR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DriveL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           TLR,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           TLL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BLR,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           BLL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
static const float ticksPerInch = 0.95 * (627.2 / (4.0 * PI));
//adjust to compensate for wheel slip
static const float ticksPerRev = 1.11 * (ticksPerInch * 14.5 * PI);

static const float ticksPerLiftInch = 627.2 / 12.0;

static const int upSpeed = 127;

static const int downSpeed = -64;

void move(float dist, int speed, bool hold)
{
	resetMotorEncoder(DriveR);
	resetMotorEncoder(DriveL);

	setMotorTarget(DriveR, dist*ticksPerInch, speed, hold);
	setMotorTarget(DriveL, dist*ticksPerInch, speed, hold);

	while (!getMotorTargetCompleted(DriveR) && !getMotorTargetCompleted(DriveL))
		wait1Msec(10);
}

void spin(float dist, int speed, bool hold)
{
	resetMotorEncoder(DriveR);
	resetMotorEncoder(DriveL);

	setMotorTarget(DriveR, dist*ticksPerRev, speed, hold);
	setMotorTarget(DriveL, -dist*ticksPerRev, speed, hold);

	while (!getMotorTargetCompleted(DriveR) && !getMotorTargetCompleted(DriveL))
		wait1Msec(10);
}

void lift(float height, int speed, bool hold)
{
	setMotorTarget(BLL,	height * ticksPerLiftInch, speed, hold);
	setMotorTarget(BLR, height * ticksPerLiftInch, speed, hold);

	while (!getMotorTargetCompleted(BLL) && !getMotorTargetCompleted(BLR))
		wait1Msec(10);
}


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	resetMotorEncoder(BLL);
	resetMotorEncoder(BLR);

  //pinching and picking up cone
	motor[Claw] = -20;
	//motor[liftMotor] = -100;
	//wait1Msec(400);
	//motor[liftMotor] = -15;
	setMotorTarget(Claw,  (int)(45.0 * Claw), 100, true);

	//moving to the goal
	move(47.0, 127, true);

	//dropping the cone
	motor[Claw] = 90;
	wait1Msec(1000);
	motor[Claw] = 0;

	move(-9.0, 63, true);

	spin(0.125, 63, false);

	//lowering the lift

	move(9.0, 63, false);

	//closing the hand
	motor[Claw] = -100;
	wait1Msec(1000);
	motor[Claw] = -40;

	wait1Msec(200);

	//lifting the lift

	//while (!getMotorTargetCompleted(liftMotor)) {
	//	wait1Msec(10);
	//}

	move(-9.0, 53, false);

	spin(-0.125, 53, false);

	move(10.0, 53, false);

	//dropping the second cone
	motor[Claw] = 100;
	wait1Msec(1000);
	motor[Claw] = 0;
}






/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

	nMotorPIDSpeedCtrl[DriveL] = RegIdle;
	nMotorPIDSpeedCtrl[DriveR] = RegIdle;
	nMotorPIDSpeedCtrl[BLL] = RegIdle;
	nMotorPIDSpeedCtrl[BLR] = RegIdle;

	while (true)
  {
  		//Assigns the value of the Y1 axis to the left motor
		motor[DriveL] = vexRT[Ch3];
		//Assigns the value of the Y2 axis to the right motor
		motor[DriveR] = vexRT[Ch2];

		//If button 6 up (right bumper) is pressed
		if(vexRT[Btn6U] == 1)
		{
			//Raise the lift
			motor[BLR] = upSpeed;
		}
		//Else, if button 6 down (right trigger) is pressed
		else if(vexRT[Btn6D] == 1)
		{
			//Lower the lift
			motor[BLR] = downSpeed;
		}
		//Else (no button pressed)
		else
		{
			//Turn the lift motor off
			motor[BLR] = 0;
		}

		if(vexRT[Btn5U] == 1)
		{
			//Raise the lift
			motor[BLL] = upSpeed;
		}
		//Else, if button 6 down (right trigger) is pressed
		else if(vexRT[Btn5D] == 1)
		{
			//Lower the lift
			motor[BLL] = downSpeed;
		}
		//Else (no button pressed)
		else
		{
			//Turn the lift motor off
			motor[BLL] = 0;
		}

		// 7L / 7R controls the hand
		if(vexRT[Btn7L] == 1)
			motor[Claw] = 100;
		else if(vexRT[Btn7R] == 1)
			motor[Claw] = -100;
		else
			motor[Claw] = 0;
  }
}
