#pragma config(Motor,	 port2,						rightMotor,		 tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,	 port3,						leftMotor,		 tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,	 port4,						armMotor,			 tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,	 port5,						armHand,			 tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(OFF)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "JoystickDriver.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void accel(int startSpeed, int endSpeed, int pause)
{
	if (startSpeed < endSpeed)
	{
		for(int j = startSpeed; j < endSpeed; j++)
		{
			motor[leftMotor] = j;
			motor[rightMotor] = j;
			wait1Msec(pause);
		}
	}
	else
	{
			for(int j = startSpeed; j > endSpeed; j--)
		{
			motor[leftMotor] = j;
			motor[rightMotor] = j;
			wait1Msec(pause);
		}
	}
}

task usercontrol()
{
  // User control code here, inside the loop

	while (true)
	{
		while (!vexRT[Btn8U])
			; // wait
	  accel(0, 127, 2);
		wait1Msec(500);
		accel(127, 0, 2);
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec (1000);
		motor[armHand] = -100;
		wait1Msec(600);
		motor[armHand] = -20;
		motor[armMotor] = -100;
		wait1Msec(400);
		motor[armMotor] = -10;
		motor[rightMotor] = -90;
		motor[leftMotor] = 90;
		wait1Msec (190);
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
		motor[rightMotor] = 100;
		motor[leftMotor] = 100;
		wait1Msec(500);
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
		motor[rightMotor] = 70;
		motor[leftMotor] = -70;
		wait1Msec(190);
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
		while (!vexRT[Btn8D])
			;
			motor[armMotor] = 0;
			motor[armHand] = 0;
	}

  while (false)
  {
		//Assigns the value of the Y1 axis to the left motor
		motor[leftMotor] = vexRT[Ch3];
		//Assigns the value of the Y2 axis to the right motor
		motor[rightMotor] = vexRT[Ch2];

		//If button 6 up (right bumper) is pressed
		if(vexRT[Btn6U] == 1)
		{
			//Raise the arm
			motor[armMotor] = -100;
		}
		//Else, if button 6 down (right trigger) is pressed
		else if(vexRT[Btn6D] == 1)
		{
			//Lower the arm
			motor[armMotor] = 100;
		}
		//Else (no button pressed)
		else
		{
			//Turn the arm motor off
			motor[armMotor] = 0;
		}

		// 7L / 7R controls the hand
		if(vexRT[Btn7L] == 1)
			motor[armHand] = 100;
		else if(vexRT[Btn7R] == 1)
			motor[armHand] = -100;
		else
			motor[armHand] = 0;
	}
}
