#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           hand,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(2000);
	motor[rightMotor] = 127;
	motor[leftMotor]  = 127;
	wait1Msec(3000);
	motor[rightMotor] =0;
	motor[leftMotor] =0;

	motor[rightMotor] = -127;
	motor[leftMotor] = 127;
	wait1Msec(3000);
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;

	motor[arm]= -30;
  wait1Msec(1000);
  motor[arm]= 0;

	motor[rightMotor] = 127;
  motor [leftMotor] = 127;
  wait1Msec(3000);
  motor[rightMotor] =0;
  motor[leftMotor] =0;

  motor[hand] = 127;
  wait1Msec(1000);

  motor[hand] = -127;
  wait1Msec(1000);
  }
