#pragma config(Motor,	 port2,						rightMotor,		 tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,	 port3,						leftMotor,		 tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,	 port4,						armMotor,			 tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,	 port5,						hand,					 tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "JoystickDriver.c"

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}


task usercontrol()
{
	//Infinite Loop
	while(true)
	{
		// Update buttons and joysticks
//		getJoystickSettings(joystick);

		//Assigns the value of the Y1 axis to the left motor
		motor[leftMotor] = vexRT[Ch3];
		//Assigns the value of the Y2 axis to the right motor
		motor[rightMotor] = vexRT[Ch2];

		//If button 6 (right bumper) is pressed
		if(joy1Btn(06) == 1)
		{
			//Raise the arm
			motor[armMotor] = 100;
		}

		//Else, if button 8 (right trigger) is pressed
		else if(joy1Btn(08) == 1)
		{
			//Lower the arm
			motor[armMotor] = -100;
		}

		//Else (no button pressed)
		else
		{
			//Turn the arm motor off
			motor[armMotor] = 0;
		}

		// wait1Msec(2000);
		//motor[rightMotor] = 127;
		//motor[leftMotor]	= 127;
		//wait1Msec(3000);
		//motor[rightMotor] =0;
		//motor[leftMotor] =0;

		//motor[rightMotor] = -127;
		//motor[leftMotor] = 127;
		//wait1Msec(3000);
		//motor[rightMotor] = 0;
		//motor[leftMotor] = 0;

		//motor[arm]= -30;
		// wait1Msec(1000);
		// motor[arm]= 0;

		//motor[rightMotor] = 127;
		// motor [leftMotor] = 127;
		// wait1Msec(3000);
		// motor[rightMotor] =0;
		// motor[leftMotor] =0;

		// motor[hand] = 127;
		// wait1Msec(1000);

		// motor[hand] = -127;
		// wait1Msec(1000);
	}
}
